<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Trombinoscope HajjariKarima</title>
		<p>Trombinoscope HajjariKarima THYP1415</p>
        <meta charset="UTF-8">
    </head>
    <body>
        
       
		<?php
		public function sauvegarderAction()
    {
    	$xml=simplexml_load_file( "http://picasaweb.google.com/data/feed/base/user/107401320610499259896/albumid/6065229773950541889?alt=rss&kind=photo&authkey=Gv1sRgCNak7e60l-7VlgE&hl=fr");
    	//$feed = file_get_contents();
    
    	$connex = $this->connexbd();
    	foreach ($xml->channel->item as $photo)//parcourir le tableau de photo
    	{
    		$nometu = $photo->title;
    		$source = $photo->enclosure['url'];
    		$connex->exec("select * from etudiant");
    	}
    }
?>
    </body>
</html>


